version: '3.8'

services:
  frontend:
    build:
      context: ./cloudfront
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host

  backend:
    build:
      context: ./cloudback
    ports:
      - "8000:8000"  # Map port 8000 in the container to port 8000 on the host
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=mydatabase
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=mysecretpassword
    depends_on:
      - db
    volumes:
      - ./cloudback:/djangoback

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
