version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: cloudback/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cloudback:/djangoback
    environment:
      - DB_HOST=mysql
      - DB_NAME=kitchen_db
      - DB_USER=root
      - DB_PASSWORD=examplepassword
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: cloudfront/Dockerfile
    ports:
      - "3000:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: kitchen_db
      MYSQL_USER: root
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
