# Generated by Django 5.0.2 on 2024-03-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addfood', '0002_addfood_category_addfood_delivertime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfood',
            old_name='deliverTime',
            new_name='orderFrom',
        ),
        migrations.RenameField(
            model_name='addfood',
            old_name='orderTime',
            new_name='orderTill',
        ),
    ]
