# Generated by Django 5.0.2 on 2024-03-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addfood', '0004_addfood_fooffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addfood',
            old_name='foofFile',
            new_name='foodFile',
        ),
    ]
