# Generated by Django 5.0.2 on 2024-03-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addarea', '0002_addarea_selectedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarea',
            name='selectedFile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
