# Generated by Django 5.0.2 on 2024-03-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addarea', '0003_alter_addarea_selectedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addarea',
            name='selectedFile',
        ),
    ]
