# Generated by Django 5.0.2 on 2024-03-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemakerreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemakerreg',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
