# Generated by Django 5.0.2 on 2024-03-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfood',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addfood',
            name='deliverTime',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='addfood',
            name='orderTime',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='addfood',
            name='price',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='addfood',
            name='userId',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
