# Generated by Django 5.0.2 on 2024-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addfood', '0006_alter_addfood_foodfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfood',
            name='foodFile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
