# Generated by Django 5.0.2 on 2024-03-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addorder',
            old_name='kitchenName',
            new_name='kitchenId',
        ),
    ]
