# Generated by Django 5.0.2 on 2024-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_kitchenname_addorder_kitchenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='addorder',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
